### PR TITLE
Revert "Revert "pages: add project arcs, project cards""

### PR DESCRIPTION
**Pull request by gordoncc**
Reverts urbit/roadmap.urbit.org#15

- Renames lead to owner
- Makes contributors linkable to their Urbit ID pages
- Adds landing pages for arcs
- Adds project cards, uses them on all pages
- Adds a footer to the site

### CODE REVIEW

**Comment by gordoncc** [comment]
@matildepark this is looking pretty good to me.

A few color things to tweak:

Match project arc tag colors
Screen Shot 2022-11-23 at 12 35 49 PM

Match next up card bgcolor
Screen Shot 2022-11-23 at 12 38 14 PM

Match dark mode cards bgcolor
Screen Shot 2022-11-23 at 12 41 45 PM

**Comment by gordoncc** [comment]
Another design update – remove status from the page heading (e.g. Current Projects) and add it with its card appearance just above the project title.
Screen Shot 2022-11-23 at 12 45 17 PM

**Comment by gordoncc** [comment]
And let's add the specification metadata link to the project page itself
Screen Shot 2022-11-23 at 12 53 05 PM

**Comment by matildepark** [comment]
The trouble is that some of the colours here both aren’t in our palette (so for purple I had to guess using your mock and the relevant opacity) and that they would need to be defined in the toml, so they’re injected programmatically, which means Tailwind can’t see them, so they might not be generated. The status colours are using our palette otherwise, and the designs diverge.

**Comment by gordoncc** [comment]
Let's add some colors to our palette then.

**Comment by gordoncc** [comment]
Oh and one other thing – can we change the target of the links in the overview so that they don't open in a new window?

**Comment by matildepark** [comment]
> Oh and one other thing – can we change the target of the links in the overview so that they don't open in a new window?

They usually don't if the URL has urbit.org in it. Because of the custom deploy, they do.

**Comment by matildepark** [comment]
Oh wait, I see. Links just need to start with a slash. I'll do.

**Comment by matildepark** [comment]
I found a way around the arc thing — let me push.

**Comment by matildepark** [comment]
Anything I'm missing? @gordoncc

**Comment by gordoncc** [comment]
Colors look great.

One last to do – the little call to action to dm the project owner on the project pages.

Screen Shot 2022-11-23 at 3 40 19 PM

**Comment by matildepark** [comment]
As long as it isn't completed, I assume?

**Comment by gordoncc** [comment]
> As long as it isn't completed, I assume?

Oh yes, that would make sense.

**Comment by gordoncc** [comment]
Looks good, rock and roll

**Pull request merged**
